export const SOURCES = [
  {id:'sana-en',publisherId:'sana',name:'SANA English',feedUrl:'https://sana.sy/en/feed/',sourceUrl:'https://sana.sy/en/',publisherLocation:'Syria',coverage:['Syria'],language:'en',sourceType:'primary_institutional',accessMethod:'RSS + public article',limitations:'State news agency; attribute claims and corroborate disputed developments.'},
  {id:'north-press-en',publisherId:'north-press',name:'North Press Agency',feedUrl:'https://npasyria.com/en/feed/',sourceUrl:'https://npasyria.com/en/',publisherLocation:'Syria',coverage:['Syria'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public article',limitations:'Regional publisher; site availability varies.'},
  {id:'enab-baladi-en',publisherId:'enab-baladi',name:'Enab Baladi English',feedUrl:'https://english.enabbaladi.net/feed/',sourceUrl:'https://english.enabbaladi.net/',publisherLocation:'Syria',coverage:['Syria'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public article',limitations:'English edition does not cover every Arabic-edition report.'},
  {id:'dhaka-tribune',publisherId:'dhaka-tribune',name:'Dhaka Tribune',feedUrl:'https://www.dhakatribune.com/feed/',sourceUrl:'https://www.dhakatribune.com/',publisherLocation:'Bangladesh',coverage:['Bangladesh'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public article',limitations:'Feed is broad; article markup may change.'},
  {id:'daily-star-bangladesh',publisherId:'daily-star',name:'The Daily Star — Bangladesh',feedUrl:'https://www.thedailystar.net/news/bangladesh/rss.xml',sourceUrl:'https://www.thedailystar.net/news/bangladesh',publisherLocation:'Bangladesh',coverage:['Bangladesh'],language:'en',sourceType:'independent_reporting',accessMethod:'section RSS + public article metadata/body when accessible',limitations:'Some pages may provide only metadata or be access-limited.'},
  {id:'daily-star-business',publisherId:'daily-star',name:'The Daily Star — Business',feedUrl:'https://www.thedailystar.net/business/rss.xml',sourceUrl:'https://www.thedailystar.net/business',publisherLocation:'Bangladesh',coverage:['Bangladesh'],language:'en',sourceType:'independent_reporting',accessMethod:'section RSS + public article metadata/body when accessible',limitations:'Some pages may provide only metadata or be access-limited.'},
  {id:'myjoyonline',publisherId:'myjoyonline',name:'MyJoyOnline',feedUrl:'https://www.myjoyonline.com/feed/',sourceUrl:'https://www.myjoyonline.com/',publisherLocation:'Ghana',coverage:['Ghana'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public article',limitations:'May carry agency or partner reports; wire origin is detected per article where possible.'},
  {id:'graphic-ghana',publisherId:'graphic-ghana',name:'Graphic Online',feedUrl:'https://www.graphic.com.gh/news/general-news.feed?type=rss',sourceUrl:'https://www.graphic.com.gh/news/general-news.html',publisherLocation:'Ghana',coverage:['Ghana'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public article',limitations:'Joomla markup and bot controls may change.'},
  {id:'ghanaweb',publisherId:'ghanaweb',name:'GhanaWeb',feedUrl:'https://www.ghanaweb.com/GhanaHomePage/NewsArchive/rss.xml',sourceUrl:'https://www.ghanaweb.com/GhanaHomePage/NewsArchive/',publisherLocation:'Ghana',coverage:['Ghana'],language:'en',sourceType:'republication_mixed',accessMethod:'RSS + public article',limitations:'Original provenance varies; republications do not count as independent corroboration.'},
  {id:'toronto-city',publisherId:'toronto-city',name:'City of Toronto News',feedUrl:'https://www.toronto.ca/news/feed/',sourceUrl:'https://www.toronto.ca/news/',publisherLocation:'Toronto, Canada',coverage:['GTA'],language:'en',sourceType:'primary_institutional',accessMethod:'RSS + public release',limitations:'Primary municipal statement, not independent corroboration.'},
  {id:'cbc-toronto',publisherId:'cbc',name:'CBC Toronto',feedUrl:'https://www.cbc.ca/cmlink/rss-canada-toronto',sourceUrl:'https://www.cbc.ca/news/canada/toronto',publisherLocation:'Canada',coverage:['GTA'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public metadata/body when accessible',limitations:'Article-body accessibility varies.'},
  {id:'cbc-canada',publisherId:'cbc',name:'CBC Canada',feedUrl:'https://www.cbc.ca/cmlink/rss-canada',sourceUrl:'https://www.cbc.ca/news/canada',publisherLocation:'Canada',coverage:['Canada'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public metadata/body when accessible',limitations:'Article-body accessibility varies.'},
  {id:'aljazeera-all',publisherId:'aljazeera',name:'Al Jazeera',feedUrl:'https://www.aljazeera.com/xml/rss/all.xml',sourceUrl:'https://www.aljazeera.com/',publisherLocation:'Qatar',coverage:['Middle East','World'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public article',limitations:'Broad feed; attribution and conflict-reporting uncertainty must be retained.'},
  {id:'bbc-world',publisherId:'bbc',name:'BBC World',feedUrl:'https://feeds.bbci.co.uk/news/world/rss.xml',sourceUrl:'https://www.bbc.com/news/world',publisherLocation:'United Kingdom',coverage:['World'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public metadata/body when accessible',limitations:'Some pages are dynamic.'},
  {id:'bbc-technology',publisherId:'bbc',name:'BBC Technology',feedUrl:'https://feeds.bbci.co.uk/news/technology/rss.xml',sourceUrl:'https://www.bbc.com/news/technology',publisherLocation:'United Kingdom',coverage:['World'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public metadata/body when accessible',limitations:'Some pages are dynamic.'},
  {id:'guardian-world',publisherId:'guardian',name:'The Guardian World',feedUrl:'https://www.theguardian.com/world/rss',sourceUrl:'https://www.theguardian.com/world',publisherLocation:'United Kingdom',coverage:['World'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public article',limitations:'Publisher access and licensing remain publisher-controlled.'},
  {id:'guardian-science',publisherId:'guardian',name:'The Guardian Science',feedUrl:'https://www.theguardian.com/science/rss',sourceUrl:'https://www.theguardian.com/science',publisherLocation:'United Kingdom',coverage:['World'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public article',limitations:'Publisher access and licensing remain publisher-controlled.'},
  {id:'npr-world',publisherId:'npr',name:'NPR World',feedUrl:'https://feeds.npr.org/1004/rss.xml',sourceUrl:'https://www.npr.org/sections/world/',publisherLocation:'United States',coverage:['World'],language:'en',sourceType:'independent_reporting',accessMethod:'RSS + public article',limitations:'US-oriented international selection.'},
];

export const KNOWN_SOURCE_FAILURES = [
  {name:'Bangladesh Sangbad Sangstha',url:'https://www.bssnews.net/feed',status:'blocked',detail:'Cloudflare challenge returned HTTP 403 to the bounded collector.'},
  {name:'The Daily Star front page',url:'https://www.thedailystar.net/frontpage/rss.xml',status:'retired_from_registry',detail:'Feed served old 2022 items; current section feeds replaced it.'},
  {name:'The Business Standard',url:'https://www.tbsnews.net/rss.xml',status:'retired_from_registry',detail:'Feed served 2019–2021 items.'},
  {name:'Ontario Newsroom',url:'https://news.ontario.ca/en/rss',status:'retired_from_registry',detail:'URL returns an HTML application shell, not RSS.'},
];
