const STOP=new Set('a an and are as at be by for from has have in into is it its of on or that the their this to was were will with global issues news says said'.split(' '));
// Keep short action stems bounded explicitly. A loose `ban\w*` pattern, for
// example, incorrectly classified "Bangladesh" as the action "ban".
const ACTION=/\b(?:meet(?:s|ing)?|met|discuss\w*|address\w*|speech(?:es)?|announc\w*|approv\w*|grant\w*|vot\w*|ban(?:ned|ning|s)?|attack\w*|strike\w*|kill\w*|launch\w*|call\w*|reopen\w*|extend\w*|maintain\w*|rais\w*|cut(?:s|ting)?|sign\w*|return\w*|protest\w*|rall\w*|arrest\w*|elect\w*|appoint\w*|resign\w*|investigat\w*)\b/gi;
const COUNTRY=/\b(Bangladesh|Bangladeshi|Pakistan|Pakistani|Iran|Iranian|Israel|Israeli|Syria|Syrian|Ghana|Ghanaian|Canada|Canadian|Ethiopia|Ethiopian|China|Chinese|United States|US|Palestinian|Palestine|India|Indian)\b/gi;
const words=s=>[...new Set(String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>2&&!STOP.has(x)))];
const overlap=(a,b)=>{const B=new Set(b);return a.filter(x=>B.has(x));};
const entities=s=>[...new Set([...(String(s||'').match(COUNTRY)||[]).map(x=>x.toLowerCase().replace(/bangladeshi/,'bangladesh').replace(/pakistani/,'pakistan').replace(/iranian/,'iran').replace(/israeli/,'israel').replace(/syrian/,'syria').replace(/ghanaian/,'ghana').replace(/canadian/,'canada').replace(/ethiopian/,'ethiopia').replace(/chinese/,'china').replace(/palestinian/,'palestine').replace(/indian/,'india')),...[...String(s||'').matchAll(/\b[A-Z][a-z]{2,}(?:\s+[A-Z][a-z]{2,}){1,2}\b/g)].map(m=>m[0].toLowerCase())])];
const actions=s=>[...new Set([...String(s||'').matchAll(ACTION)].map(m=>{const x=m[0].toLowerCase();if(x==='met'||x.startsWith('meet'))return'meet';for(const stem of ['discuss','address','speech','announce','approve','grant','vote','attack','strike','kill','launch','call','reopen','extend','maintain','raise','cut','sign','return','protest','rall','arrest','elect','appoint','resign','investigat'])if(x.startsWith(stem))return stem==='rall'?'rally':stem;if(/^ban(?:ned|ning|s)?$/.test(x))return'ban';return x}))];
const countries=s=>[...new Set((String(s||'').match(COUNTRY)||[]).map(x=>x.toLowerCase().replace(/bangladeshi/,'bangladesh').replace(/pakistani/,'pakistan').replace(/iranian/,'iran').replace(/israeli/,'israel').replace(/syrian/,'syria').replace(/ghanaian/,'ghana').replace(/canadian/,'canada').replace(/ethiopian/,'ethiopia').replace(/chinese/,'china').replace(/palestinian/,'palestine').replace(/indian/,'india')))];
export function buildCentralEvent(selected,packet){const story=selected.title||selected.selectedTitle||'',text=[story,...(selected.memberArticles||[]).map(x=>x.title)].join(' '),a=actions(text);return {event_id:selected.eventId,selected_story:story,actors:entities(text),action:a.join(', ')||'development described by selected story',location:(packet.geographicClassification?.eventLocations||[]).map(x=>x.name),time_window:packet.eventTimeOrWindow||[]};}
export function classifyFragments(selected,packet){const central=buildCentralEvent(selected,packet),centralTerms=words(central.selected_story),centralEntities=central.actors,centralActions=actions(central.selected_story),centralCountries=countries(central.selected_story),sources=[{sourceId:packet.primaryNarrativeSource?.sourceId||packet.primary_source_id,role:'primary',facts:packet.coreFactualPropositions||[]} ,...(packet.secondarySourceAdditions||[]).map(x=>({sourceId:x.sourceId,role:'secondary',facts:x.completeFactualPropositions||[]}))],fragments=[];
  for(const source of sources){let current='central',sourceIndex=0;for(const fact of source.facts){sourceIndex++;const fTerms=words(fact),fEntities=entities(fact),fActions=actions(fact),fCountries=countries(fact),sharedTerms=overlap(centralTerms,fTerms),sharedEntities=overlap(centralEntities,fEntities),sharedActions=overlap(centralActions,fActions),newEntities=fEntities.filter(x=>!centralEntities.includes(x)),newCountries=fCountries.filter(x=>!centralCountries.includes(x)),newEventCue=fActions.length>0&&newEntities.length>0;const hardTransition=/\b(?:separately|in another)\b/i.test(fact)||/\b(?:later met|had a meeting with)\b/i.test(fact);const alsoActorShift=/\balso\b/i.test(fact)&&newCountries.length>0&&fActions.includes('meet');const datedNewScene=sourceIndex>1&&/^On\s+(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)\b/i.test(fact)&&fActions.length>0&&(/\b(?:airport|hospital|headquarters|parliament|embassy|border|city|village|town|province|district)\b/i.test(fact)||newEntities.length>=2);const separateCue=(hardTransition&&fActions.length>0)||alsoActorShift||datedNewScene;let membership,reason;
      const strongCentralReturn=sharedTerms.length>=3||(sharedEntities.length>=2&&sharedActions.length>=1);
      if(separateCue){membership='separate_event';reason='explicit transition introduces a different actor/action, country pairing or dated scene';current='separate_event';}
      else if(current==='separate_event'&&!strongCentralReturn){membership='separate_event';reason='continuation of a separate event section in the source article';}
      else if(sharedTerms.length>=2||sharedEntities.length>=1&&sharedActions.length>=1){membership='central';reason='shares selected event actors/action or multiple high-specificity title terms';current='central';}
      else if(current==='central'){membership='supporting_context';reason='contiguous context within the selected event section and no deterministic separate-event transition';}
      else {membership='ambiguous';reason='insufficient deterministic connection to the selected central event';}
      fragments.push({fragment_id:`F${String(fragments.length+1).padStart(2,'0')}`,source_id:source.sourceId,source_role:source.role,text:fact,event_membership:membership,reason,signals:{shared_terms:sharedTerms,shared_entities:sharedEntities,shared_actions:sharedActions,new_entities:newEntities}});
    }}return {central_event:central,fragments,included:fragments.filter(x=>['central','supporting_context'].includes(x.event_membership)),excluded:fragments.filter(x=>!['central','supporting_context'].includes(x.event_membership))};}
export function buildBoundPacket(selected,packet,{temporal}){const scoped=classifyFragments(selected,packet),primaryId=packet.primaryNarrativeSource?.sourceId||packet.primary_source_id,primaryFacts=scoped.included.filter(x=>x.source_id===primaryId).map(x=>x.text),secondary=(packet.secondarySourceAdditions||[]).map(s=>({...s,completeFactualPropositions:scoped.included.filter(x=>x.source_id===s.sourceId).map(x=>x.text)})).filter(x=>x.completeFactualPropositions.length);return {...packet,central_event_to_explain:scoped.central_event,temporal_context:temporal,allowed_exact_dates:temporal.allowed_exact_dates.map(x=>x.date),writer_focus_instructions:['CENTRAL EVENT TO EXPLAIN: '+scoped.central_event.selected_story,'Do not expand supporting context into a second co-equal event. Every page must primarily explain this central event.','Do not invent an exact calendar date when event_date is unresolved. Preserve supported relative wording where natural; otherwise omit the exact date.'],evidence_fragments:scoped.fragments,coreFactualPropositions:primaryFacts,primaryNarrativeSource:{...packet.primaryNarrativeSource,completeFactualPropositions:primaryFacts},secondarySourceAdditions:secondary};}
export function detectCrossPacketOverlap(boundPackets,{includedOnly=false}={}){const out=[];const fragments=packet=>(packet.evidence_fragments||[]).filter(f=>!includedOnly||['central','supporting_context'].includes(f.event_membership));for(let i=0;i<boundPackets.length;i++)for(let j=i+1;j<boundPackets.length;j++){const A=boundPackets[i],B=boundPackets[j],bTerms=words(B.central_event_to_explain.selected_story),bEntities=B.central_event_to_explain.actors,bActions=actions(B.central_event_to_explain.selected_story);for(const f of fragments(A)){const st=overlap(words(f.text),bTerms),se=overlap(entities(f.text),bEntities),sa=overlap(actions(f.text),bActions);if((st.length>=3&&sa.length>=1)||(se.length>=2&&sa.length>=1))out.push({packet_event_id:A.eventId,other_event_id:B.eventId,fragment_id:f.fragment_id,membership:f.event_membership,reason:`fragment overlaps other central event: terms=${st.join(',')}; entities=${se.join(',')}; actions=${sa.join(',')}`});}const aTerms=words(A.central_event_to_explain.selected_story),aEntities=A.central_event_to_explain.actors,aActions=actions(A.central_event_to_explain.selected_story);for(const f of fragments(B)){const st=overlap(words(f.text),aTerms),se=overlap(entities(f.text),aEntities),sa=overlap(actions(f.text),aActions);if((st.length>=3&&sa.length>=1)||(se.length>=2&&sa.length>=1))out.push({packet_event_id:B.eventId,other_event_id:A.eventId,fragment_id:f.fragment_id,membership:f.event_membership,reason:`fragment overlaps other central event: terms=${st.join(',')}; entities=${se.join(',')}; actions=${sa.join(',')}`});}}return out;}
