const MONTHS={january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12};
const WEEKDAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const pad=n=>String(n).padStart(2,'0'),isoDate=(y,m,d)=>`${y}-${pad(m)}-${pad(d)}`;
function validDate(y,m,d){const x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d;}
export function dateInTimezone(timestamp,timeZone){if(!timestamp||!timeZone)return null;const d=new Date(timestamp);if(!Number.isFinite(d.getTime()))return null;const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',weekday:'long'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return {date:`${parts.year}-${parts.month}-${parts.day}`,year:+parts.year,month:+parts.month,day:+parts.day,weekday:parts.weekday,timeZone};}
function addDays(date,delta){const [y,m,d]=date.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+delta));return isoDate(x.getUTCFullYear(),x.getUTCMonth()+1,x.getUTCDate());}
function weekdayIndex(date){const [y,m,d]=date.split('-').map(Number);return new Date(Date.UTC(y,m-1,d)).getUTCDay();}
export function validateWeekdayDate(weekday,date){const i=WEEKDAYS.findIndex(x=>x.toLowerCase()===String(weekday).toLowerCase());return i>=0&&/^\d{4}-\d{2}-\d{2}$/.test(date)&&weekdayIndex(date)===i;}
export function resolveRelativeDate(rawExpression,{publicationTime,timeZone}={}){const raw=String(rawExpression||'').trim(),base=dateInTimezone(publicationTime,timeZone),unresolved=reason=>({raw_expression:raw,resolved_date:null,resolution_status:'unresolved',basis:reason});if(!base)return unresolved('source publication timestamp and source timezone are both required');const v=raw.toLowerCase().replace(/^on\s+/,'').trim();if(v==='today')return {raw_expression:raw,resolved_date:base.date,resolution_status:'resolved',basis:`source publication date in ${timeZone}`};if(v==='yesterday')return {raw_expression:raw,resolved_date:addDays(base.date,-1),resolution_status:'resolved',basis:`one calendar day before source publication date in ${timeZone}`};let last=false,w=v.match(/^last\s+(sunday|monday|tuesday|wednesday|thursday|friday|saturday)$/i);if(w)last=true;else w=v.match(/^(sunday|monday|tuesday|wednesday|thursday|friday|saturday)$/i);if(!w)return unresolved('expression is outside the supported deterministic resolver');const target=WEEKDAYS.findIndex(x=>x.toLowerCase()===w[1].toLowerCase()),current=weekdayIndex(base.date);if(!last&&target===current)return unresolved('same-weekday wording is ambiguous between publication day and the prior week');let delta=(current-target+7)%7;if(delta===0)delta=7;const date=addDays(base.date,-delta);return {raw_expression:raw,resolved_date:date,resolution_status:'resolved',basis:`most recent ${WEEKDAYS[target]} before source publication date in ${timeZone}`};}
export function extractRelativeExpressions(text){const raw=String(text||''),masked=raw.replace(/[“\"][^”\"]*[”\"]/g,m=>' '.repeat(m.length)),out=[];for(const m of masked.matchAll(/\b(today|yesterday|(?:on\s+)?(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)|last\s+(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday))\b/gi))if(!out.some(x=>x.toLowerCase()===m[0].toLowerCase()))out.push(m[0]);return out;}
export function extractExplicitDates(text){const found=[];for(const m of String(text||'').matchAll(/\b(\d{4})-(\d{2})-(\d{2})\b/g)){const y=+m[1],mo=+m[2],d=+m[3];if(validDate(y,mo,d))found.push({raw:m[0],date:isoDate(y,mo,d)});}for(const m of String(text||'').matchAll(/\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2}),\s+(\d{4})\b/gi)){const mo=MONTHS[m[1].toLowerCase()],d=+m[2],y=+m[3];if(validDate(y,mo,d))found.push({raw:m[0],date:isoDate(y,mo,d)});}return [...new Map(found.map(x=>[x.date,x])).values()];}
export function extractWeekdayDatePairs(text){const out=[];for(const m of String(text||'').matchAll(/\b(Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday),?\s+(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2}),\s+(\d{4})\b/gi)){const date=isoDate(+m[4],MONTHS[m[2].toLowerCase()],+m[3]);out.push({raw:m[0],weekday:m[1],date,valid:validDate(+m[4],MONTHS[m[2].toLowerCase()],+m[3])&&validateWeekdayDate(m[1],date)});}return out;}
export function buildTemporalContext(packet,{sourceTimezone=null}={}){const facts=[...(packet.coreFactualPropositions||[]),...(packet.secondarySourceAdditions||[]).flatMap(x=>x.completeFactualPropositions||[])],text=facts.join(' '),relative=extractRelativeExpressions(text),resolutions=relative.map(x=>resolveRelativeDate(x,{publicationTime:packet.sourcePublicationTime,timeZone:sourceTimezone})),explicit=extractExplicitDates(text),allowed=new Map(explicit.map(x=>[x.date,{date:x.date,role:'explicit_source_date',basis:x.raw}]));for(const r of resolutions)if(r.resolution_status==='resolved')allowed.set(r.resolved_date,{date:r.resolved_date,role:'deterministically_resolved_relative_date',basis:r.basis,raw_expression:r.raw_expression});const resolvedPrimary=resolutions.find(x=>x.resolution_status==='resolved')?.resolved_date??null;return {publication_time:packet.sourcePublicationTime||null,article_updated_time:packet.sourceUpdateTime||null,event_date:resolvedPrimary,event_time:null,statement_date:null,as_of_date:null,relative_time_expression:relative,relative_resolutions:resolutions,allowed_exact_dates:[...allowed.values()]};}
export function validateGeneratedDates(card,temporal){const text=[card?.headline,...(card?.pages||[]).map(x=>x.text),...(card?.uncertainties||[])].join(' '),exact=extractExplicitDates(text),weekdayPairs=extractWeekdayDatePairs(text),allowed=new Set((temporal.allowed_exact_dates||[]).map(x=>x.date)),unsupported=exact.filter(x=>!allowed.has(x.date)),invalidWeekdayPairs=weekdayPairs.filter(x=>!x.valid);return {valid:unsupported.length===0&&invalidWeekdayPairs.length===0,generated_exact_dates:exact,allowed_exact_dates:[...allowed],unsupported_exact_dates:unsupported,weekday_date_pairs:weekdayPairs,invalid_weekday_date_pairs:invalidWeekdayPairs,status:unsupported.length||invalidWeekdayPairs.length?'date_validation_failure':'pass'};}
export function writerTemporalInstructions(temporal){const resolved=temporal.event_date?`Event date: ${temporal.event_date} (deterministically resolved from source-relative wording).`:'Exact event date: not established by the supplied source.';const wording=temporal.relative_time_expression.length?`Source wording: ${temporal.relative_time_expression.map(x=>`"${x}"`).join(', ')}.`:'';return `${resolved} ${wording} Do not invent an exact calendar date that is not in allowed_exact_dates. Publication/update time is not event time.`.trim();}
